SELECT
MIN(CASE WHEN OCCUPATION = 'Doctor' THEN NAME ELSE NULL END) AS 'DOCTOR',
MIN(CASE WHEN OCCUPATION = 'Professor' THEN NAME ELSE NULL END) AS 'PROFESSOR',
MIN(CASE WHEN OCCUPATION = 'Singer' THEN NAME ELSE NULL END) AS 'SINGER',
MIN(CASE WHEN OCCUPATION = 'Actor' THEN NAME ELSE NULL END) AS 'ACTOR'
FROM (SELECT a.Occupation, a.Name, (SELECT COUNT(*) FROM OCCUPATIONS AS b WHERE a.Occupation = b.Occupation AND a.Name > b.Name) AS rank FROM OCCUPATIONS AS a) AS c
GROUP BY c.rank
GO