SELECT 
CASE WHEN GRADE < 8 THEN NULL ELSE NAME END AS NAME, 
GRADE, MARKS AS MARK FROM STUDENTS
JOIN GRADES ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY Grade DESC, NAME, MARK